
services:
  # ------------------------------------------------------------
  # REDIS (Banco de dados para o SSE)
  # O c처digo Python no VS Code vai acessar via localhost:6379
  # ------------------------------------------------------------
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379" # Mapeia a porta do container para o seu PC

  # ------------------------------------------------------------
  # RABBITMQ (Mensageria)
  # O c처digo Python no VS Code vai acessar via localhost:5672
  # ------------------------------------------------------------
  rabbitmq:
    image: "rabbitmq:3-management" # Vers찾o com painel visual
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta de conex찾o (protocolo AMQP usado pelo pika)
      - "15672:15672" # Porta do painel administrativo (acesse no navegador)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5